### ISSUE TITLE
Milestone 1 Cleanup

### ISSUE THREAD

**Issue by arek-kwapis** [Abstrat-Technologies/rustedanvil#21]
Items required for Milestone 1 to close

- [ ] Issues resolved
  - [ ] #14 
    - [ ] Documentation
    - [ ] Resolution 
    - [ ] Spinoff into Milestone 2
  - [ ] #8
  - [ ] #15 
    - [ ] Documentation
    - [ ] Fixes
      - [ ] Theoretical
      - [ ] Application
  - [ ] #16 
    - [ ] Documentation
    - [ ] Fixes
      - [ ] Theoretical
      - [ ] Application
  - [ ] #20 
- [ ] Documentation
- [ ] Updated information
- [ ] Prepare workspace
  - [x] Synch locals
  - [ ] Synch remote
  - [x] Synch forks
  - [ ] VSC
    - [ ] workspace 
    - [ ] git
- [ ] Prepare repo
  - [x] Remove unnecessary files
  - [ ] Update README
  - [ ] Milestone info
  - [ ] Discussions cleanup
  - [ ] Issue board cleanup
  - [ ] Tags (#27)
  - [ ] Wiki prep (#20) 
  - [ ] #32
  - [ ] Security prep
  - [ ] templates (#27)
  - [ ] internal settings

**Comment by Unloaded123456** [comment]
Looks like documentation tasks has been completed
